name: my_simple_notes
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  path: ^1.9.0
  riverpod_annotation: ^2.6.1
  sqflite: ^2.3.3+1
  uuid: ^4.5.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11


flutter:

  uses-material-design: true
